CREATE TABLE IF NOT EXISTS user(
    id BIGINT(11) AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    birth DATE NOT NULL,
    password VARCHAR(255) NOT NULL,
    register DATETIME NOT NULL,
    weight FLOAT(5,2) NOT NULL,
    PRIMARY KEY(id)
);